spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: Shivam@4017
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto:update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect